version: "3"

services:

  todo:
    build:
      context: .
    container_name: todo
    image: todo:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - todo-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql:/mysql:3306/todo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306
      - SPRING_PROFILES_ACTIVE=form

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3310:3306
    networks:
      - todo-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES:s3
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  todo-network:

volumes:
  database: